embeddings {
tensor_name: "max3:00000"
tensor_path: "00000/max3/tensors.tsv"
metadata_path: "00000/max3/metadata.tsv"
sprite {
image_path: "00000/max3/sprite.png"
single_image_dim: 28
single_image_dim: 28
}
}
embeddings {
tensor_name: "act1:00000"
tensor_path: "00000/act1/tensors.tsv"
metadata_path: "00000/act1/metadata.tsv"
sprite {
image_path: "00000/act1/sprite.png"
single_image_dim: 28
single_image_dim: 28
}
}
embeddings {
tensor_name: "act2:00000"
tensor_path: "00000/act2/tensors.tsv"
metadata_path: "00000/act2/metadata.tsv"
sprite {
image_path: "00000/act2/sprite.png"
single_image_dim: 28
single_image_dim: 28
}
}
embeddings {
tensor_name: "out:00000"
tensor_path: "00000/out/tensors.tsv"
metadata_path: "00000/out/metadata.tsv"
sprite {
image_path: "00000/out/sprite.png"
single_image_dim: 28
single_image_dim: 28
}
}
